name: 'Automatic Tests'

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [ opened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set .NET Version
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build
      
    - name: Test
      run: dotnet test